### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by damnms** [chkuendig/tv7-epg-parser#1]
Hi, i use a epg.xml file from https://github.com/mathewmeconry/TV7_EPG_Data at the moment and stumbled upon your project which looks very promising. can you give some more information how to start the .py?
When i start it in pycharm, it seems like its missing something:

```
/home/oli/PycharmProjects/tv7/.venv/bin/python /home/oli/PycharmProjects/tv7/tv7-epg-parser.py 
Traceback (most recent call last):
  File "/home/oli/PycharmProjects/tv7/tv7-epg-parser.py", line 179, in <module>
    _downloadFile(filename, url)
  File "/home/oli/PycharmProjects/tv7/tv7-epg-parser.py", line 157, in _downloadFile
    open(filename, 'wb').write(r.content)
    ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/tvChannelList.json'
```

So i debugged and noticed, its missing the "tmp" folder.
Would it be possible to test for that and if it does not exist, create it?

I am now testing your app. Would be awesome if that works, thanks!

**Comment by chkuendig** [comment]
Did you manage to run it once you created the tmp folder?

**Comment by damnms** [comment]
Yes, i created the tmp folder myself and let it run. The .xml has been produced. Thanks! 
But somehow i am having problems with iptvsimple to recognize the new .xml (some sort of caching probably).

Would be awesome to have this in pip somehow, so it could easily be installed with pip on any distribution supporting pip without the need for .venv etc.

**Comment by chkuendig** [comment]
Great, thanks for confirming. I pushed the fix I did yesterday to add an empty dir ( 9346183bd10cda3dd3e3553e0637871dc3ed8429 ).

I don't have any plans to push this into pip right now.
